[package]
name = "client"
version = "0.1.0"
edition = "2018"

[dependencies]
shared = { path = "../shared" }
rust_decimal = "1.16"
chrono = "0.4"
tokio = { version = "1.12", features = ["rt", "net", "sync", "time"] }
log = "0.4"
bincode = "1.3"